version: '3.7'

services:
  iredmail:
    image: iredmail/mariadb:stable
    hostname: mail.stsecurity.moe
    container_name: iredmail
    restart: unless-stopped
    volumes:
      - backup_mysql:/var/vmail/backup/mysql
      - clamav:/var/lib/clamav
      - custom:/opt/iredmail/custom
      - imapsieve_copy:/var/vmail/imapsieve_copy
      - mailboxes:/var/vmail/vmail1
      - mlmmj:/var/vmail/mlmmj
      - mlmmj_archive:/var/vmail/mlmmj-archive
      - mysql:/var/lib/mysql
      - postfix_queue:/var/spool/postfix
      - sa_rules:/var/lib/spamassassin
      - ssl:/opt/iredmail/ssl
    ports:
      - '127.0.0.1:3000:80'
      - '127.0.0.1:3001:443'
      - '110:110'
      - '995:995'
      - '143:143'
      - '993:993'
      - '25:25'
      - '465:465'
      - '587:587'
    environment:
      - HOSTNAME=mail.stsecurity.moe
      - FIRST_MAIL_DOMAIN=stsecurity.moe
      - FIRST_MAIL_DOMAIN_ADMIN_PASSWORD=xxxxxxxxxxxxx
      - MLMMJADMIN_API_TOKEN=xxxxxxxxxxxxxx
      - ROUNDCUBE_DES_KEY=xxxxxxxxxxxxxxx

volumes:
  backup_mysql:    # Backup MySQL copies
  clamav:          # ClamAV databases
  custom:          # Custom config files
  imapsieve_copy:  # Used by Dovecot plugin 'imapsieve'
  mailboxes:       # All users' mailboxes
  mlmmj:           # Mailing list data
  mlmmj_archive:   # Mailing list archive
  mysql:           # MySQL database
  postfix_queue:   # Postfix queues
  sa_rules:        # SpamAssassin rules
  ssl:             # SSL cert/key files
